### ISSUE TITLE
Enable parallelization

### ISSUE THREAD

**Issue by U8NWXD** [CovertLab/vEcoli#86]
To run colony simulations efficiently on the cloud, we need to be able to run processes as parallel processes. Vivarium Core can do this, but we need to make sure that our processes work correctly when parallelized. Specifically, we need to be able to serialize the states they see, their updates, and their constructor args. We also need to make sure that partitioned processes can pass their hidden states between requester and evolvers.

Parallelized by serializing full process:

* [x] Chromosome Structure (Requires vivarium-collective/vivarium-core#98 for `self.deriver_mode` to work correctly because process is not partitioned, so it's not serialized.)
* [x] Metabolism (~Blocked by problem destroying `SwiGLPK` objects.~)
* [x] Transcription Factor Binding
* [x] Transcript Elongation
* [x] Transcript Initiation
* [x] RNA Degradation
* [x] Polypeptide Elongation
* [x] Polypeptide Initiation
* [x] Complexation (Requires CovertLab/arrow#47 for serializing `StochasticSimulation` objects.)
* [x] Two Component System
* [x] Equilibrium
* [x] Protein Degradation
* [x] Chromosome Replication
* [x] Mass Listener (Requires vivarium-collective/vivarium-core#98 for `self.first_time_step` to work correctly because process is not partitioned, so it's not serialized.)
* [x] mRNA Counts Listener
* [x] Allocator
* [x] Requester
* [x] Evolver

Parallelized by serializing only necessary variables:

* [x] Chromosome Structure
* [x] Metabolism
* [x] Transcription Factor Binding
* [x] Transcript Elongation
* [x] Transcript Initiation
* [x] RNA Degradation
* [x] Polypeptide Elongation
* [x] Polypeptide Initiation
* [x] Complexation
* [x] Two Component System
* [x] Equilibrium
* [x] Protein Degradation
* [x] Chromosome Replication
* [x] Mass Listener
* [x] mRNA Counts Listener
* [x] Allocator

Other processes not in `ecoli_partition`:

* Cell Division
* Mass
* Shape
* Chemoreceptor Cluster
* Coarse Motor Processes
* Flagella Motor Processes
* Membrane Potential
* Diffusion Network
* Spatial Geometry
* Exchange Stub
